language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - python ./setup.py install

# command to run tests
script:
  - python -m unittest discover tests
